version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - chatbot

  chatbot:
    build: ./chatbot
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - backend
